from pybirdai.models.bird_data_model import *
from pybirdai.process_steps.pybird.orchestration import Orchestration
from pybirdai.process_steps.pybird.csv_converter import CSVConverter
from datetime import datetime
from pybirdai.annotations.decorators import lineage, track_table_init

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem:
	base = None #EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Base

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Base:
	pass

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionTable :
	EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems = [] # EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem []
	EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Credit_or_Counterparty_Risk_Exposure_Data_Table = None # Credit_or_Counterparty_Risk_Exposure_Data
	def calc_EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems(self) -> list[EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem] :
		items = [] # EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem []
		for item in self.EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Credit_or_Counterparty_Risk_Exposure_Data_Table.Credit_or_Counterparty_Risk_Exposure_Datas:
			newItem = EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem()
			newItem.base = item
			items.append(newItem)
		return items

	def init(self):
		Orchestration().init(self)
		self.EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems = []
		self.EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems.extend(self.calc_EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems())
		CSVConverter.persist_object_as_csv(self,True)
		return None


class Credit_or_Counterparty_Risk_Exposure_Data(EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Base):
	CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT = None # CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT
	def metric_value(self):
		value = self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.OWN_FUNDS_MEASURE
		if value in (None, ''):
			return 0
		try:
			numeric_value = float(value)
			return int(numeric_value) if numeric_value.is_integer() else numeric_value
		except (TypeError, ValueError):
			return 0
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.OWN_FUNDS_CALCULATION_COMPONENT"})
	def OWN_FUNDS_CALCULATION_COMPONENT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.OWN_FUNDS_CALCULATION_COMPONENT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_ADJUSTMENT"})
	def TYPE_OF_ADJUSTMENT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_ADJUSTMENT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CRM_EFFECTS_COLLATERAL"})
	def CRM_EFFECTS_COLLATERAL(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CRM_EFFECTS_COLLATERAL
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.ACCOUNTING_ITEMS_USED_AS_COLLATERAL_OR_GUARANTEE_RECEIVED"})
	def ACCOUNTING_ITEMS_USED_AS_COLLATERAL_OR_GUARANTEE_RECEIVED(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.ACCOUNTING_ITEMS_USED_AS_COLLATERAL_OR_GUARANTEE_RECEIVED
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_FINANCIAL_INSTRUMENTS_USED_IN_CREDIT_RISK_MITIGATION"})
	def TYPE_OF_FINANCIAL_INSTRUMENTS_USED_IN_CREDIT_RISK_MITIGATION(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_FINANCIAL_INSTRUMENTS_USED_IN_CREDIT_RISK_MITIGATION
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CALCULATION_METHOD"})
	def CALCULATION_METHOD(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CALCULATION_METHOD
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_CREDIT_RISK_MITIGATION"})
	def TYPE_OF_CREDIT_RISK_MITIGATION(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_CREDIT_RISK_MITIGATION
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.FLOWS_DIRECTION"})
	def FLOWS_DIRECTION(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.FLOWS_DIRECTION
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CONVERSION_FACTORS_FOR_OFF_BALANCE_SHEET_ITEMS"})
	def CONVERSION_FACTORS_FOR_OFF_BALANCE_SHEET_ITEMS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CONVERSION_FACTORS_FOR_OFF_BALANCE_SHEET_ITEMS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.APPROACH_FOR_DETERMINATION_OF_CCF"})
	def APPROACH_FOR_DETERMINATION_OF_CCF(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.APPROACH_FOR_DETERMINATION_OF_CCF
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.SPECIFIC_CONTRACT_CLAUSES"})
	def SPECIFIC_CONTRACT_CLAUSES(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.SPECIFIC_CONTRACT_CLAUSES
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TRANSITIONAL_PROVISIONS"})
	def TRANSITIONAL_PROVISIONS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TRANSITIONAL_PROVISIONS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REGULATORY_ADJUSTMENTS_INCLUDED_IN_THE_EXPOSURE"})
	def REGULATORY_ADJUSTMENTS_INCLUDED_IN_THE_EXPOSURE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REGULATORY_ADJUSTMENTS_INCLUDED_IN_THE_EXPOSURE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.USE_OF_EXTERNAL_RATINGS"})
	def USE_OF_EXTERNAL_RATINGS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.USE_OF_EXTERNAL_RATINGS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRUDENTIAL_PORTFOLIO"})
	def PRUDENTIAL_PORTFOLIO(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRUDENTIAL_PORTFOLIO
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_RISK"})
	def TYPE_OF_RISK(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_RISK
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.COUNTERPARTY_NATURE"})
	def COUNTERPARTY_NATURE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.COUNTERPARTY_NATURE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.IMPAIRMENT_STATUS"})
	def IMPAIRMENT_STATUS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.IMPAIRMENT_STATUS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REGULATORY_ASSESMENT_OF_TYPE_OF_ENTITY"})
	def REGULATORY_ASSESMENT_OF_TYPE_OF_ENTITY(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REGULATORY_ASSESMENT_OF_TYPE_OF_ENTITY
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.METHODS_TO_DETERMINE_RISK_WEIGHTS"})
	def METHODS_TO_DETERMINE_RISK_WEIGHTS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.METHODS_TO_DETERMINE_RISK_WEIGHTS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PARTIAL_USE"})
	def PARTIAL_USE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PARTIAL_USE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.APPLICABLE_CAPITAL_REGULATORY_REQUIREMENT"})
	def APPLICABLE_CAPITAL_REGULATORY_REQUIREMENT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.APPLICABLE_CAPITAL_REGULATORY_REQUIREMENT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRUDENTIAL_APPROACH_THAT_AUTHORISED_BUT_NOT_APPLIED"})
	def PRUDENTIAL_APPROACH_THAT_AUTHORISED_BUT_NOT_APPLIED(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRUDENTIAL_APPROACH_THAT_AUTHORISED_BUT_NOT_APPLIED
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.ACCOUNTING_ITEMS"})
	def ACCOUNTING_ITEMS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.ACCOUNTING_ITEMS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_FINANCIAL_INSTRUMENTS"})
	def TYPE_OF_FINANCIAL_INSTRUMENTS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_FINANCIAL_INSTRUMENTS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_CLEARING"})
	def TYPE_OF_CLEARING(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYPE_OF_CLEARING
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.RISK_WEIGHTS"})
	def RISK_WEIGHTS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.RISK_WEIGHTS
	LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT = None # LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT
	@lineage(dependencies={"LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT.PRDNTL_PRTFL_TYP"})
	def PRDNTL_PRTFL_TYP(self):
		return self.LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT.PRDNTL_PRTFL_TYP
	LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT = None # LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT
	@lineage(dependencies={"LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT.PRDNTL_PRTFL_TYP"})
	def PRDNTL_PRTFL_TYP(self):
		if self.LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT is not None:
			return self.LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT.PRDNTL_PRTFL_TYP
		if self.LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT is not None:
			return self.LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT.PRDNTL_PRTFL_TYP
		if self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT is not None:
			return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRDNTL_PRTFL_TYP
		return None
	INSTRMNT = None # INSTRMNT
	@lineage(dependencies={"INSTRMNT.INSTRMNT_TYP_PRDCT"})
	def TYP_INSTRMNT(self):
		if self.INSTRMNT is not None:
			return self.INSTRMNT.INSTRMNT_TYP_PRDCT
		if self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT is not None:
			return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_INSTRMNT
		return None

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Credit_or_Counterparty_Risk_Exposure_Data_Table:
	CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT_Table = None # CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT
	LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT_Table = None # LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT
	LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_Table = None # LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT
	INSTRMNT_Table = None # INSTRMNT
	Credit_or_Counterparty_Risk_Exposure_Datas = []# Credit_or_Counterparty_Risk_Exposure_Data[]
	def calc_Credit_or_Counterparty_Risk_Exposure_Datas(self) :
		items = [] # Credit_or_Counterparty_Risk_Exposure_Data[
		# Join up any refered tables that you need to join
		# loop through the main table
		# set any references you want to on the new Item so that it can refer to themin operations
		for item in self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT_Table:
			newItem = Credit_or_Counterparty_Risk_Exposure_Data()
			newItem.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT = item
			newItem.base = item
			items.append(newItem)
		return items
	def init(self):
		Orchestration().init(self)
		self.Credit_or_Counterparty_Risk_Exposure_Datas = []
		self.Credit_or_Counterparty_Risk_Exposure_Datas.extend(self.calc_Credit_or_Counterparty_Risk_Exposure_Datas())
		CSVConverter.persist_object_as_csv(self,True)
		return None

