from pybirdai.models.bird_data_model import *
from pybirdai.process_steps.pybird.orchestration import Orchestration
from pybirdai.process_steps.pybird.csv_converter import CSVConverter
from datetime import datetime
from pybirdai.annotations.decorators import lineage, track_table_init

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem:
	base = None #EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Base

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Base:
	pass

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionTable :
	EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems = [] # EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem []
	EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Credit_or_Counterparty_Risk_Exposure_Data_Table = None # Credit_or_Counterparty_Risk_Exposure_Data
	def calc_EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems(self) -> list[EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem] :
		items = [] # EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem []
		for item in self.EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Credit_or_Counterparty_Risk_Exposure_Data_Table.Credit_or_Counterparty_Risk_Exposure_Datas:
			newItem = EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItem()
			newItem.base = item
			items.append(newItem)
		return items

	def init(self):
		Orchestration().init(self)
		self.EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems = []
		self.EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems.extend(self.calc_EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_UnionItems())
		CSVConverter.persist_object_as_csv(self,True)
		return None


class Credit_or_Counterparty_Risk_Exposure_Data(EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Base):
	CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT = None # CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CONVERSION_FACTOR"})
	def REF_COREP_400_CONVERSION_FACTOR(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CONVERSION_FACTOR
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CRM_EFFECT"})
	def REF_COREP_400_CRM_EFFECT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CRM_EFFECT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_EXTERNAL_RATING_USE"})
	def REF_COREP_400_EXTERNAL_RATING_USE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_EXTERNAL_RATING_USE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.DFLT_STTS"})
	def DFLT_STTS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.DFLT_STTS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.APPRCH_PRDNTL_PRPSS"})
	def APPRCH_PRDNTL_PRPSS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.APPRCH_PRDNTL_PRPSS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CALCULATION_METHOD"})
	def REF_COREP_400_CALCULATION_METHOD(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CALCULATION_METHOD
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_SPECIFIC_CONTRACT_CLAUSE"})
	def REF_COREP_400_SPECIFIC_CONTRACT_CLAUSE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_SPECIFIC_CONTRACT_CLAUSE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_TRANSITIONAL_PROVISION"})
	def REF_COREP_400_TRANSITIONAL_PROVISION(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_TRANSITIONAL_PROVISION
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CLLTRL_RL_TYP"})
	def CLLTRL_RL_TYP(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.CLLTRL_RL_TYP
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_INSTRMNT"})
	def TYP_INSTRMNT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_INSTRMNT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CLEARING_TYPE"})
	def REF_COREP_400_CLEARING_TYPE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CLEARING_TYPE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_COUNTERPARTY_NATURE"})
	def REF_COREP_400_COUNTERPARTY_NATURE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_COUNTERPARTY_NATURE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_RISK_WEIGHT"})
	def REF_COREP_400_RISK_WEIGHT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_RISK_WEIGHT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_ACCNTNG_ITM"})
	def TYP_ACCNTNG_ITM(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_ACCNTNG_ITM
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_REGULATORY_ENTITY_ASSESSMENT"})
	def REF_COREP_400_REGULATORY_ENTITY_ASSESSMENT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_REGULATORY_ENTITY_ASSESSMENT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRDNTL_PRTFL_TYP"})
	def PRDNTL_PRTFL_TYP(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRDNTL_PRTFL_TYP
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_EXPOSURE_ADJUSTMENT_STAGE"})
	def REF_COREP_400_EXPOSURE_ADJUSTMENT_STAGE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_EXPOSURE_ADJUSTMENT_STAGE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_SUPPORTING_FACTOR_ADJUSTMENT"})
	def REF_COREP_400_SUPPORTING_FACTOR_ADJUSTMENT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_SUPPORTING_FACTOR_ADJUSTMENT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CREDIT_RISK_MITIGATION_TYPE"})
	def REF_COREP_400_CREDIT_RISK_MITIGATION_TYPE(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CREDIT_RISK_MITIGATION_TYPE
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_RSK"})
	def TYP_RSK(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_RSK
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_COLLATERAL_GUARANTEE_ACCOUNTING_ITEM"})
	def REF_COREP_400_COLLATERAL_GUARANTEE_ACCOUNTING_ITEM(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_COLLATERAL_GUARANTEE_ACCOUNTING_ITEM
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_NETTING_AGREEMENT_STATUS"})
	def REF_COREP_400_NETTING_AGREEMENT_STATUS(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_NETTING_AGREEMENT_STATUS
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CAPITAL_REQUIREMENT_CONDITION"})
	def REF_COREP_400_CAPITAL_REQUIREMENT_CONDITION(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_CAPITAL_REQUIREMENT_CONDITION
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_OWN_FUNDS_CALCULATION_COMPONENT"})
	def REF_COREP_400_OWN_FUNDS_CALCULATION_COMPONENT(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_OWN_FUNDS_CALCULATION_COMPONENT
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_FLOW_DIRECTION"})
	def REF_COREP_400_FLOW_DIRECTION(self):
		return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_FLOW_DIRECTION
	@lineage(dependencies={"CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_OWN_FUNDS_MEASURE"})
	def metric_value(self):
		value = self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.REF_COREP_400_OWN_FUNDS_MEASURE
		if value in (None, ''):
			return 0
		try:
			numeric_value = float(value)
			return int(numeric_value) if numeric_value.is_integer() else numeric_value
		except (TypeError, ValueError):
			return 0
	LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT = None # LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT
	@lineage(dependencies={"LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT.PRDNTL_PRTFL_TYP"})
	def PRDNTL_PRTFL_TYP(self):
		return self.LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT.PRDNTL_PRTFL_TYP
	LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT = None # LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT
	@lineage(dependencies={"LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT.PRDNTL_PRTFL_TYP"})
	def PRDNTL_PRTFL_TYP(self):
		if self.LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT is not None:
			return self.LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT.PRDNTL_PRTFL_TYP
		if self.LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT is not None:
			return self.LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT.PRDNTL_PRTFL_TYP
		if self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT is not None:
			return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.PRDNTL_PRTFL_TYP
		return None
	INSTRMNT = None # INSTRMNT
	@lineage(dependencies={"INSTRMNT.INSTRMNT_TYP_PRDCT"})
	def TYP_INSTRMNT(self):
		if self.INSTRMNT is not None:
			return self.INSTRMNT.INSTRMNT_TYP_PRDCT
		if self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT is not None:
			return self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT.TYP_INSTRMNT
		return None

class EBA_COREP_C_07_00_a_4_0_0__eba_qEC_qx1_Credit_or_Counterparty_Risk_Exposure_Data_Table:
	CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT_Table = None # CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT
	LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT_Table = None # LNG_BLNC_SHT_RCGNSD_DBT_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_DRVD_DT
	LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT_Table = None # LNG_BLNC_SHT_RCGNSD_SCRTY_PSTN_PRDNTL_PRTFL_ACCNTNG_CLSSFCTN_ASSGNMNT
	INSTRMNT_Table = None # INSTRMNT
	Credit_or_Counterparty_Risk_Exposure_Datas = []# Credit_or_Counterparty_Risk_Exposure_Data[]
	def calc_Credit_or_Counterparty_Risk_Exposure_Datas(self) :
		items = [] # Credit_or_Counterparty_Risk_Exposure_Data[
		# Join up any refered tables that you need to join
		# loop through the main table
		# set any references you want to on the new Item so that it can refer to themin operations
		for item in self.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT_Table:
			newItem = Credit_or_Counterparty_Risk_Exposure_Data()
			newItem.CNTRPRTY_OR_ISSR_EXPSR_RSK_EXPSR_DT = item
			newItem.base = item
			items.append(newItem)
		return items
	def init(self):
		Orchestration().init(self)
		self.Credit_or_Counterparty_Risk_Exposure_Datas = []
		self.Credit_or_Counterparty_Risk_Exposure_Datas.extend(self.calc_Credit_or_Counterparty_Risk_Exposure_Datas())
		CSVConverter.persist_object_as_csv(self,True)
		return None
